# Generated by Django 3.1.6 on 2021-04-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('slug', models.SlugField()),
                ('video_id', models.CharField(max_length=20, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PU', 'Publish'), ('DU', 'DRAFT')], default='DU', max_length=2)),
                ('publish_timestamp', models.DateTimeField(blank=True, null=True)),
                ('live', models.BooleanField(default=False)),
            ],
        ),
    ]
