# Generated by Django 3.1.6 on 2021-04-27 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20210427_1901'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlublishedVideoProxy',
        ),
        migrations.CreateModel(
            name='PublishedVideoProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Published Video',
                'verbose_name_plural': 'Published Videos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('videos.video',),
        ),
    ]
