# Generated by Django 3.1.6 on 2021-04-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20210427_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveVideoProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Live Video',
                'verbose_name_plural': 'Live Videos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('videos.video',),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
