# Generated by Django 3.1.6 on 2021-05-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taggeditem',
            name='objects_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
