# Generated by Django 3.1.6 on 2021-05-06 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_taggeditem_objects_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taggeditem',
            old_name='objects_id',
            new_name='object_id',
        ),
    ]
