# Generated by Django 3.1.6 on 2021-05-04 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0004_playlist_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='playlist.playlist'),
        ),
    ]
