# Generated by Django 3.1.6 on 2021-05-10 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0008_auto_20210506_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistRelated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist.playlist')),
                ('related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_item', to='playlist.playlist')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='_playlist_related_+', through='playlist.PlaylistRelated', to='playlist.Playlist'),
        ),
    ]
