# Generated by Django 3.1.6 on 2021-05-10 15:27

from django.db import migrations, models
import django.db.models.deletion
import playlist.models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0009_auto_20210510_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistrelated',
            name='related',
            field=models.ForeignKey(limit_choices_to=playlist.models.playlistRelatedLimitTo, on_delete=django.db.models.deletion.CASCADE, related_name='related_item', to='playlist.playlist'),
        ),
    ]
